spring:
  datasource:
    url: ${URL_DB}
    username: ${USER_DB}
    password: ${PASS_DB}

  jpa:
    hibernate:
      ddl-auto: update

#    properties:jdbc:mysql://localhost:3306/car_parking?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080