spring:
  datasource:
    url: ${URL_DB:jdbc:mysql://localhost:3306/car_parking_project?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true}
    username: ${USER_DB}
    password: ${PASS_DB}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

ratio-of-tax: 0.5